# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myres.Residence'),
        ),
    ]
