# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0003_auto_20170331_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
