# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0006_auto_20170405_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='info',
            field=models.TextField(blank=True, verbose_name='Additional [optional] information'),
        ),
    ]
