# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myres', '0007_auto_20170425_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='residenceuser',
            name='is_authorised',
            field=models.BooleanField(default=False),
        ),
    ]
